home:
  number_of_products: 4
categories:
  root_id: 0
  food_default_id: 1
  drink_default_id: 2
products:
  number_of_comment: 5
  star_min: 1
  star_max: 5
  out_of_stock: 0
user_models:
  max_length_name: 50
  max_length_email: 255
  min_length_password: 6
  time_expired: 2
sessions_controller:
  checked: "1"
up_edit:
  male: 1
  female: 0
filters:
  number_of_products: 8
orders:
  number_of_orders: 5
comments:
  max_length_content: 255
